### ISSUE TITLE
error due to Jinja2 API change

### ISSUE THREAD

**Issue by jboynyc** [simonw/datasette-render-images#12]
Unless I pin to an older version of jinja2, I get this error: `module 'jinja2' has no attribute 'Markup'`

This is caused by a [change](https://jinja.palletsprojects.com/en/3.1.x/changes/#version-3-1-0) introduced in the 3.1 release of Jinja2.

Unfortunately pinning is not a solution when publishing datasets to cloud providers.

**Comment by numist** [comment]
This [appears to be fixed](https://github.com/simonw/datasette-render-images/commit/f03e193c60eabcd14c128cb54d6030f81a2c0712) (edit: verified locally!) but there hasn't been a new version of datasette-render-images released since then so the fix hasn't made its way out to `pip`.

@simonw: could you press a new release?

**Comment by bobwhitelock** [comment]
Saw the same error, and installing the latest `main` from Git fixed this - @simonw can we publish a release so the default version of this plugin installed by `pip` works? Thanks!

**Comment by simonw** [comment]
Release is out, apologies for the delay. https://github.com/simonw/datasette-render-images/releases/tag/0.4
